name: push docker image to ACR

on :
  workflow_dispatch:
      inputs:
        name:
         description: "Select Realse Branch"
         default: "master"
env:
  IMAGE_NAME: ambackbackend

jobs:
  build:
    name: Build container image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Log into registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ACR_ENDPOINT }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name : Build & Push
        run: |
             docker compose build
             docker images
             docker push ${{ secrets.ACR_ENDPOINT }}/${{ env.IMAGE_NAME }}:latest
          
     # - name: Build & Push
     #   uses: docker/build-push-action@v2
     #   with:
     #     push: true
     #     build-args: |
     #       version=${{ github.sha }}
     #     tags: ${{ secrets.ACR_ENDPOINT }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
