name: Deploy Images to FE

on :
  workflow_dispatch:
         
jobs:
      tigger-frontend : 
        runs-on: ubuntu-latest
        steps:
          - name: Trigger Other Workflow
            uses: actions/github-script@v6
            with:
              github-token: ${{ secrets.GH_TOKEN }}
              script: |
                await github.repos.createDispatchEvent({
                owner: 'engineerscodes',
                repo: 'AMBA-FE',
                workflow_id: 'tigger-gha-test.yml'
                event_type: 'triggered_by_be_repo',
                client_payload:  {
                      amba_branch: '${{github.ref_name}}'
                   }
                });
