name: Deploy Images to FE

on :
  workflow_dispatch:
         
jobs:
      tigger-frontend : 
        runs-on: ubuntu-latest
        steps:
          - name: Trigger Other Workflow
            uses: actions/github-script@v6
            with:
              github-token: ${{ secrets.GH_TOKEN }}
              script: |
                github.rest.repos.createDispatchEvent({
                  owner: 'engineerscodes',
                  repo: 'AMBA-FE',
                  event_type: 'triggered_by_repo_a',
                  client_payload: {
                      amba_branch: 'Test'
                   }
                })
